// Generated by scripts/generate_pharma_contracts.py. Do not edit by hand.

export type Id = string;

export type Timestamp = string;

export type Hash = string;

export type Source = "ctgov" | "pubmed";

export type Role = "reader" | "analyst" | "reviewer" | "admin";

export type DateValue = {
  value: string | null;
  precision: "day" | "month" | "year" | "unknown";
  kind: "source_reported" | "estimated" | "actual" | "unknown";
};

export type Error = {
  error: {
    code: string;
    message: string;
    details: Record<string, unknown>;
    request_id: string;
  };
};

export type Message = {
  message: string;
};

export type User = {
  id: Id;
  email: string;
  display_name: string;
  is_active: boolean;
};

export type Membership = {
  workspace_id: Id;
  workspace_name: string;
  role: Role;
  data_mode?: "demo" | "live";
};

export type Me = {
  user: User;
  memberships: Array<Membership>;
  csrf_token: string;
};

export type LoginRequest = {
  email: string;
  password: string;
};

export type Member = {
  user: User;
  role: Role;
  enabled: boolean;
};

export type RoleUpdate = {
  role: Role;
};

export type DrugInput = {
  display_name: string;
  development_code?: string | null;
  description?: string | null;
  indications?: Array<string>;
  targets?: Array<string>;
};

export type Drug = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  display_name: string;
  development_code: string | null;
  description: string | null;
  indications: Array<string>;
  targets: Array<string>;
  revision: number;
  archived: boolean;
  updated_at: Timestamp;
};

export type AliasInput = {
  alias: string;
  namespace: "common_name" | "development_code" | "source_name" | "other";
  evidence_id?: Id | null;
  note: string;
};

export type Alias = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  drug_id: Id;
  alias: string;
  namespace: "common_name" | "development_code" | "source_name" | "other";
  evidence_id: Id | null;
  note: string;
  status: "pending" | "approved" | "rejected" | "revoked";
  proposed_by: Id;
  reviewed_by: Id | null;
};

export type DecisionInput = {
  decision: "approve" | "reject" | "revoke";
  note: string;
};

export type EntityLinkInput = {
  record_id: Id;
  drug_id: Id;
  relation:
    | "investigational"
    | "comparator"
    | "background"
    | "unspecified"
    | "mentions";
  evidence_id?: Id | null;
  note: string;
};

export type EntityLink = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  record_id: Id;
  drug_id: Id;
  relation:
    | "investigational"
    | "comparator"
    | "background"
    | "unspecified"
    | "mentions";
  evidence_id: Id | null;
  note: string;
  status: "pending" | "approved" | "rejected" | "revoked";
};

export type Coverage = {
  source: Source;
  status: "complete" | "partial" | "failed" | "not_requested";
  records_count: number;
  truncated: boolean;
  as_of: Timestamp | null;
  limitations: Array<string>;
};

export type SourceHealth = {
  source: Source;
  enabled: boolean;
  configured: boolean;
  state: "healthy" | "degraded" | "unavailable" | "unknown";
  last_success_at: Timestamp | null;
  last_error_code: string | null;
};

export type SourceUpdate = {
  enabled: boolean;
};

export type SyncInput = {
  sources: Array<Source>;
  drug_ids: Array<Id>;
  mode: "discovery" | "refresh_linked";
  record_limit?: number;
};

export type Job = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  kind: "ingest" | "research" | "delivery";
  state:
    | "queued"
    | "running"
    | "retry_wait"
    | "succeeded"
    | "failed"
    | "cancelled";
  attempt: number;
  error_code: string | null;
  progress: {
    processed: number;
    total: number | null;
  };
  coverage: Array<Coverage>;
};

export type TrialProjection = {
  title: string;
  raw_status: string | null;
  status:
    | "NOT_YET_RECRUITING"
    | "RECRUITING"
    | "ENROLLING_BY_INVITATION"
    | "ACTIVE_NOT_RECRUITING"
    | "SUSPENDED"
    | "TERMINATED"
    | "COMPLETED"
    | "WITHDRAWN"
    | "UNKNOWN"
    | "OTHER";
  phases: Array<string>;
  conditions: Array<string>;
  sponsor: string | null;
  enrollment: {
    count: number;
    type: "estimated" | "actual" | "unknown";
  } | null;
  has_results: boolean | null;
  source_updated: DateValue;
  start_date?: DateValue;
  primary_completion_date?: DateValue;
  completion_date?: DateValue;
  interventions?: Array<{
    name: string;
    type: string | null;
    description: string | null;
    arm_group_labels: Array<string>;
  }>;
  primary_outcomes: Array<{
    measure: string;
    description: string | null;
    time_frame: string | null;
  }>;
};

export type PublicationProjection = {
  title: string;
  authors: Array<string>;
  journal: string | null;
  doi: string | null;
  pmid: string;
  publication_date: DateValue;
  abstract_text: string | null;
  publication_types: Array<string>;
  correction_relations: Array<{
    relation: string;
    external_id: string;
  }>;
};

export type Trial = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  source: Source;
  external_id: string;
  kind: "trial";
  canonical_url: string;
  current_snapshot_id: Id | null;
  current_observation_id: Id | null;
  updated_at: Timestamp;
  is_demo: boolean;
  current_projection: TrialProjection;
};

export type Publication = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  source: Source;
  external_id: string;
  kind: "publication";
  canonical_url: string;
  current_snapshot_id: Id | null;
  current_observation_id: Id | null;
  updated_at: Timestamp;
  is_demo: boolean;
  current_projection: PublicationProjection;
};

export type SourceSnapshot = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  record_id: Id;
  content_hash: Hash;
  normalizer_version: string;
  raw_payload: Record<string, unknown>;
  normalized: TrialProjection | PublicationProjection;
  source_updated: DateValue;
  first_observed_at: Timestamp;
  is_demo: boolean;
};

export type Observation = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  record_id: Id;
  snapshot_id: Id | null;
  observation_seq: number;
  fetched_at: Timestamp;
  outcome: "baseline" | "changed" | "unchanged" | "unavailable" | "failed";
  error_code: string | null;
};

export type Locator =
  | {
      kind: "json_pointer";
      path: string;
    }
  | {
      kind: "text_range";
      section: string;
      start: number;
      end: number;
    };

export type Evidence = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  snapshot_id: Id;
  locator: Locator;
  quoted_text: string;
  snippet_hash: Hash;
  original_language: string;
  translation_text: string | null;
  extractor_version: string;
};

export type Change = {
  path: string;
  type: "added" | "removed" | "changed";
  before: unknown;
  after: unknown;
};

export type Diff = {
  record_id: Id;
  before_observation_id: Id;
  after_observation_id: Id;
  changes: Array<Change>;
  evidence_ids: Array<Id>;
};

export type Event = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  record_id: Id;
  category:
    | "status_change"
    | "enrollment_change"
    | "date_change"
    | "outcome_definition_change"
    | "results_available"
    | "publication_added"
    | "correction"
    | "other";
  title: string;
  latest_revision_id: Id | null;
  updated_at: Timestamp;
};

export type EventRevision = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  event_id: Id;
  revision_no: number;
  before_observation_id: Id;
  after_observation_id: Id;
  changes: Array<Change>;
  evidence_ids: Array<Id>;
  severity: "info" | "important" | "correction";
  observed_at: Timestamp;
};

export type TimeRange = {
  start: Timestamp;
  end_exclusive: Timestamp;
  timezone: string;
};

export type Budget = {
  max_tool_calls?: number;
  max_model_calls?: number;
  max_wall_seconds?: number;
  max_records?: number;
};

export type Usage = {
  tool_calls: number;
  model_calls: number;
  input_tokens: number | null;
  output_tokens: number | null;
  usage_quality: "reported" | "estimated" | "unknown";
  estimated_cost: number | null;
  currency: string | null;
};

export type ResearchInput = {
  question: string;
  drug_ids: Array<Id>;
  time_range: TimeRange;
  source_allowlist: Array<Source>;
  budget?: Budget;
  parent_run_id?: Id | null;
};

export type RunStatus =
  | "queued"
  | "running"
  | "awaiting_input"
  | "verifying"
  | "completed"
  | "partial"
  | "failed"
  | "cancelling"
  | "cancelled"
  | "recovery_required";

export type ResearchRun = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  created_by: Id;
  question: string;
  status: RunStatus;
  runtime_mode: "replay" | "deerflow";
  attempt: number;
  frozen_request: ResearchInput;
  usage: Usage;
  coverage: Array<Coverage>;
  stop_reason: string | null;
  event_seq: number;
  report_id: Id | null;
  updated_at: Timestamp;
  clarification?: {
    question_id?: string;
    question?: string;
    options?: Array<string>;
  } | null;
};

export type ClarificationInput = {
  answer: string;
  question_id: string;
};

export type RetryInput = {
  reason: string;
};

export type ToolCall = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  run_id: Id;
  tool: string;
  call_key: string;
  state: "started" | "completed" | "failed" | "cancelled";
  arguments_summary: Record<string, unknown>;
  evidence_ids: Array<Id>;
  error_code: string | null;
  duration_ms: number | null;
};

export type EvidenceLink = {
  evidence_id: Id;
  relation: "supports" | "contradicts" | "context";
};

export type ClaimDraft = {
  claim_key: string;
  statement: string;
  category: "fact" | "hypothesis" | "gap";
  qualifiers: {
    population: string | null;
    trial_ids: Array<Id>;
    time_scope: string | null;
    limitations: Array<string>;
  };
  evidence_links: Array<EvidenceLink>;
};

export type ResearchScope = {
  drug_ids: Array<Id>;
  time_range: TimeRange;
  knowledge_cutoff: Timestamp;
};

export type ResearchOutput = {
  schema_version: "1.0";
  title: string;
  summary: string;
  scope: ResearchScope;
  coverage: Array<Coverage>;
  sections: Array<{
    heading: string;
    text: string;
    claim_keys: Array<string>;
  }>;
  claims: Array<ClaimDraft>;
  limitations: Array<string>;
  unanswered_questions: Array<string>;
  event_revision_ids: Array<Id>;
};

export type Claim = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  claim_key: string;
  statement: string;
  category: "fact" | "hypothesis" | "gap";
  qualifiers: {
    population: string | null;
    trial_ids: Array<Id>;
    time_scope: string | null;
    limitations: Array<string>;
  };
  evidence_links: Array<EvidenceLink>;
  report_version_id: Id;
  verification_status:
    | "unverified"
    | "supported"
    | "conflicted"
    | "insufficient";
  numeric_check:
    | "passed"
    | "failed"
    | "not_applicable"
    | "manual_check_required";
};

export type Report = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  run_id: Id;
  title: string;
  created_by: Id;
  state:
    | "draft"
    | "in_review"
    | "changes_requested"
    | "approved"
    | "published"
    | "retracted";
  current_version_id: Id | null;
  published_version_id: Id | null;
  updated_at: Timestamp;
};

export type ReportVersion = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  report_id: Id;
  version_no: number;
  content: ResearchOutput;
  content_hash: Hash;
  created_by: Id;
  runtime_mode: "replay" | "deerflow";
  claim_ids: Array<Id>;
};

export type ReportVersionInput = {
  base_version_id: Id;
  content: ResearchOutput;
  edit_note: string;
};

export type VersionAction = {
  version_id: Id;
  content_hash: Hash;
};

export type ReviewInput = {
  version_id: Id;
  content_hash: Hash;
  decision: "approve" | "request_changes";
  note: string;
};

export type Review = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  version_id: Id;
  content_hash: Hash;
  decision: "approve" | "request_changes";
  note: string;
  reviewer_id: Id;
};

export type RetractInput = {
  version_id: Id;
  reason: string;
};

export type Schedule = {
  frequency: "daily" | "weekly";
  local_time: string;
  weekday: number | null;
  timezone: string;
};

export type SubscriptionInput = {
  name: string;
  drug_ids: Array<Id>;
  source_allowlist: Array<Source>;
  schedule: Schedule;
  channels: Array<"in_app" | "email">;
  enabled: boolean;
};

export type Subscription = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  name: string;
  drug_ids: Array<Id>;
  source_allowlist: Array<Source>;
  schedule: Schedule;
  channels: Array<"in_app" | "email">;
  enabled: boolean;
  owner_id: Id;
  revision: number;
  next_run_at: Timestamp | null;
  last_outcome: "generated" | "no_change" | "partial" | "failed" | null;
};

export type SchedulePreview = {
  occurrences: Array<{
    utc: Timestamp;
    local: string;
    dst_adjusted: boolean;
  }>;
};

export type Occurrence = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  subscription_id: Id;
  scheduled_at: Timestamp;
  state:
    | "queued"
    | "running"
    | "generated"
    | "no_change"
    | "partial"
    | "failed"
    | "cancelled";
  run_id: Id | null;
};

export type Delivery = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  report_id: Id;
  report_version_id: Id;
  recipient_user_id: Id;
  channel: "in_app" | "email";
  state: "queued" | "sending" | "accepted" | "unknown" | "failed" | "cancelled";
  accepted_at: Timestamp | null;
  read_at: Timestamp | null;
  error_code: string | null;
};

export type Dashboard = {
  watched_drugs: number;
  events_last_7_days: number;
  pending_reviews: number;
  source_health: Array<SourceHealth>;
  as_of: Timestamp;
  is_demo: boolean;
};

export type Audit = {
  id: Id;
  workspace_id: Id;
  created_at: Timestamp;
  actor_id: Id | null;
  action: string;
  target_type: string;
  target_id: Id | null;
  details: Record<string, unknown>;
};

export type RunEvent = {
  schema_version: "1.0";
  run_id: Id;
  seq: number;
  occurred_at: Timestamp;
  type:
    | "run.queued"
    | "run.started"
    | "plan.updated"
    | "tool.started"
    | "tool.completed"
    | "tool.failed"
    | "evidence.added"
    | "clarification.required"
    | "report.ready"
    | "run.partial"
    | "run.completed"
    | "run.failed"
    | "run.cancel_requested"
    | "run.cancelled"
    | "run.recovery_required";
  payload: Record<string, unknown>;
};

export type DrugPage = {
  items: Array<Drug>;
  next_cursor: string | null;
  has_more: boolean;
};

export type AliasPage = {
  items: Array<Alias>;
  next_cursor: string | null;
  has_more: boolean;
};

export type EntityLinkPage = {
  items: Array<EntityLink>;
  next_cursor: string | null;
  has_more: boolean;
};

export type TrialPage = {
  items: Array<Trial>;
  next_cursor: string | null;
  has_more: boolean;
};

export type PublicationPage = {
  items: Array<Publication>;
  next_cursor: string | null;
  has_more: boolean;
};

export type SourceSnapshotPage = {
  items: Array<SourceSnapshot>;
  next_cursor: string | null;
  has_more: boolean;
};

export type ObservationPage = {
  items: Array<Observation>;
  next_cursor: string | null;
  has_more: boolean;
};

export type EvidencePage = {
  items: Array<Evidence>;
  next_cursor: string | null;
  has_more: boolean;
};

export type EventPage = {
  items: Array<Event>;
  next_cursor: string | null;
  has_more: boolean;
};

export type EventRevisionPage = {
  items: Array<EventRevision>;
  next_cursor: string | null;
  has_more: boolean;
};

export type ResearchRunPage = {
  items: Array<ResearchRun>;
  next_cursor: string | null;
  has_more: boolean;
};

export type ToolCallPage = {
  items: Array<ToolCall>;
  next_cursor: string | null;
  has_more: boolean;
};

export type ReportPage = {
  items: Array<Report>;
  next_cursor: string | null;
  has_more: boolean;
};

export type ReportVersionPage = {
  items: Array<ReportVersion>;
  next_cursor: string | null;
  has_more: boolean;
};

export type ReviewPage = {
  items: Array<Review>;
  next_cursor: string | null;
  has_more: boolean;
};

export type SubscriptionPage = {
  items: Array<Subscription>;
  next_cursor: string | null;
  has_more: boolean;
};

export type OccurrencePage = {
  items: Array<Occurrence>;
  next_cursor: string | null;
  has_more: boolean;
};

export type DeliveryPage = {
  items: Array<Delivery>;
  next_cursor: string | null;
  has_more: boolean;
};

export type AuditPage = {
  items: Array<Audit>;
  next_cursor: string | null;
  has_more: boolean;
};

export type MemberPage = {
  items: Array<Member>;
  next_cursor: string | null;
  has_more: boolean;
};

export type SourceHealthList = {
  items: Array<SourceHealth>;
};

export type DrugPatch = {
  display_name?: string;
  development_code?: string | null;
  description?: string | null;
  indications?: Array<string>;
  targets?: Array<string>;
};

export type SubscriptionPatch = {
  name?: string;
  drug_ids?: Array<Id>;
  source_allowlist?: Array<Source>;
  schedule?: Schedule;
  channels?: Array<"in_app" | "email">;
  enabled?: boolean;
};

export type MemberUpdate = {
  role?: Role;
  enabled?: boolean;
};

export type ClaimPage = {
  items: Array<Claim>;
  next_cursor: string | null;
  has_more: boolean;
};

export type ReportNotice = {
  id: Id;
  workspace_id: Id;
  report_id: Id;
  version_id: Id;
  event_revision_id: Id | null;
  type: "source_updated" | "report_retracted";
  message: string;
  created_at: Timestamp;
};

export type ReportNoticePage = {
  items: Array<ReportNotice>;
  next_cursor: string | null;
  has_more: boolean;
};

export type WorkspaceConfiguration = {
  data_mode: "demo" | "live";
  model_configured: boolean;
  email_enabled: boolean;
  demo_day: number | null;
};

export type DemoAdvance = {
  day: number;
};

export type JobPage = {
  items: Array<Job>;
  next_cursor: string | null;
  has_more: boolean;
};
