#!/usr/bin/env python3
"""Generate TypeScript DTOs and deployed OpenAPI from the reviewed API contract."""

import argparse
import json
import sys
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from app.pharma.contract import specification  # noqa: E402


def ts_type(schema):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "enum" in schema:
        return " | ".join(
            json.dumps(value, ensure_ascii=False) for value in schema["enum"]
        )
    if "const" in schema:
        return json.dumps(schema["const"], ensure_ascii=False)
    if "anyOf" in schema or "oneOf" in schema:
        return " | ".join(
            ts_type(value) for value in schema.get("anyOf", schema.get("oneOf", []))
        )
    value = schema.get("type")
    if isinstance(value, list):
        return " | ".join(ts_type({**schema, "type": item}) for item in value)
    if value == "array":
        return f"Array<{ts_type(schema.get('items', {}))}>"
    if value == "object" or "properties" in schema:
        properties = schema.get("properties", {})
        if not properties:
            return "Record<string, unknown>"
        required = schema.get("required", [])
        return (
            "{\n"
            + "\n".join(
                f"  {json.dumps(key)}{'' if key in required else '?'}: {ts_type(child)};"
                for key, child in properties.items()
            )
            + "\n}"
        )
    return {
        "integer": "number",
        "number": "number",
        "string": "string",
        "boolean": "boolean",
        "null": "null",
    }.get(value, "unknown")


def generate():
    data = specification()
    data["servers"] = [
        {"url": "/", "description": "Same-origin PharmaScount deployment"}
    ]
    data["paths"] = {
        "/api/pharma" + key if key in ("/healthz", "/readyz") else key: value
        for key, value in data["paths"].items()
    }
    types = (
        "// Generated by scripts/generate_pharma_contracts.py. Do not edit by hand.\n\n"
    )
    for name, schema in data["components"]["schemas"].items():
        types += f"export type {name} = {ts_type(schema)};\n\n"
    prettier = ROOT / "frontend/node_modules/prettier/bin/prettier.cjs"
    if not prettier.exists():
        raise SystemExit(
            "Install frontend dependencies before generating its contract types."
        )
    types = subprocess.run(
        ["node", str(prettier), "--stdin-filepath", "src/core/pharma/contracts.ts"],
        input=types,
        capture_output=True,
        text=True,
        encoding="utf-8",
        check=True,
        cwd=ROOT / "frontend",
    ).stdout
    return {
        ROOT / "frontend/src/core/pharma/contracts.ts": types,
        ROOT / "backend/app/pharma/resources/openapi.generated.json": json.dumps(
            data, ensure_ascii=False, indent=2
        )
        + "\n",
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    for path, content in generate().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Generated contract stale: {path.relative_to(ROOT)}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(path.relative_to(ROOT))


if __name__ == "__main__":
    main()
